// =============================================================
// lib/constants.js — All colors, data, and translations
// =============================================================
export const ORANGE = "#FF5F00";
export const DARK   = "#1a1a2e";
export const GREEN  = "#059669";
export const BLUE   = "#1D4ED8";
export const PURPLE = "#7C3AED";
export const RED    = "#DC2626";
export const GOLD   = "#D97706";
export const CARD   = "#ffffff";
// =============================================================
// src/constants.js
// All colors, data, and translations used across the app
// =============================================================


// ── SBI codes (Dutch KVK official sector codes) ───────────────
export const SBI_MAP = {
  "تكنولوجيا المعلومات والبرمجيات":{ code:"62",          desc:"Ontwikkelen en produceren van software" },
  "ذكاء اصطناعي وبيانات":          { code:"62.09/63.11", desc:"Data- en AI-diensten" },
  "أمن سيبراني":                    { code:"62.09",       desc:"Overige IT-diensten" },
  "تجارة إلكترونية":                { code:"47.91",       desc:"Detailhandel via internet" },
  "تجارة تجزئة":                    { code:"47",          desc:"Detailhandel" },
  "تجارة جملة وتوزيع":             { code:"46",          desc:"Groothandel" },
  "خدمات مهنية واستشارات":         { code:"70.22",       desc:"Adviesbureaus bedrijfsbeheer" },
  "خدمات مالية وتأمين":            { code:"64/65",       desc:"Financiële instellingen" },
  "محاسبة وقانون":                  { code:"69",          desc:"Rechtskundige activiteiten" },
  "عقارات وإنشاءات":               { code:"41/68",       desc:"Bouwnijverheid en vastgoed" },
  "تصنيع وصناعة":                   { code:"10-33",       desc:"Industrie" },
  "لوجستيات ونقل":                 { code:"49/52",       desc:"Vervoer en opslag" },
  "صحة ورعاية طبية":               { code:"86/87/88",    desc:"Gezondheidszorg" },
  "صيدلة وتكنولوجيا حيوية":       { code:"21/72.11",    desc:"Farmaceutische industrie" },
  "تعليم وتدريب":                  { code:"85",          desc:"Onderwijs" },
  "سياحة وضيافة وفنادق":          { code:"55/56",       desc:"Logies en horeca" },
  "أغذية ومشروبات":                { code:"10/11",       desc:"Voedings- en genotmiddelen" },
  "زراعة وبيئة":                   { code:"01/02",       desc:"Landbouw en milieu" },
  "طاقة متجددة واستدامة":         { code:"35.11",       desc:"Hernieuwbare energie" },
  "إعلام وترفيه وإنتاج":          { code:"59/60",       desc:"Film en media" },
  "تصميم وإبداع وفنون":           { code:"74.10",       desc:"Gespecialiseerde ontwerp" },
  "رياضة ولياقة بدنية":           { code:"93.11/93.13", desc:"Sport en recreatie" },
  "منظمات غير ربحية واجتماعية":  { code:"88/94",       desc:"Maatschappelijke dienstverlening" },
  "حكومة وقطاع عام":              { code:"84",          desc:"Openbaar bestuur" },
  "خدمات شخصية وتجميل":          { code:"96.02",       desc:"Kappers en schoonheidsverzorging" },
  "IT & Software":                 { code:"62",          desc:"Ontwikkelen en produceren van software" },
  "AI & Data":                     { code:"62.09/63.11", desc:"Data- en AI-diensten" },
  "Cybersecurity":                 { code:"62.09",       desc:"Overige IT-diensten" },
  "E-commerce":                    { code:"47.91",       desc:"Detailhandel via internet" },
  "Retail":                        { code:"47",          desc:"Detailhandel" },
  "Detailhandel":                  { code:"47",          desc:"Detailhandel" },
  "Wholesale & Distribution":      { code:"46",          desc:"Groothandel" },
  "Groothandel & Distributie":     { code:"46",          desc:"Groothandel" },
  "Professional Services & Consulting": { code:"70.22",  desc:"Adviesbureaus" },
  "Professionele diensten & Advies":    { code:"70.22",  desc:"Adviesbureaus" },
  "Financial Services & Insurance":     { code:"64/65",  desc:"Financiële instellingen" },
  "Financiële diensten & Verzekering":  { code:"64/65",  desc:"Financiële instellingen" },
  "Accounting & Legal":            { code:"69",          desc:"Rechtskundige activiteiten" },
  "Accountancy & Juridisch":       { code:"69",          desc:"Rechtskundige activiteiten" },
  "Real Estate & Construction":    { code:"41/68",       desc:"Bouwnijverheid" },
  "Vastgoed & Bouw":               { code:"41/68",       desc:"Bouwnijverheid" },
  "Manufacturing & Industry":      { code:"10-33",       desc:"Industrie" },
  "Productie & Industrie":         { code:"10-33",       desc:"Industrie" },
  "Logistics & Transport":         { code:"49/52",       desc:"Vervoer en opslag" },
  "Logistiek & Transport":         { code:"49/52",       desc:"Vervoer en opslag" },
  "Healthcare & Medical":          { code:"86/87/88",    desc:"Gezondheidszorg" },
  "Zorg & Medisch":                { code:"86/87/88",    desc:"Gezondheidszorg" },
  "Pharma & Biotech":              { code:"21/72.11",    desc:"Farmaceutische industrie" },
  "Farma & Biotech":               { code:"21/72.11",    desc:"Farmaceutische industrie" },
  "Education & Training":          { code:"85",          desc:"Onderwijs" },
  "Onderwijs & Training":          { code:"85",          desc:"Onderwijs" },
  "Tourism & Hospitality":         { code:"55/56",       desc:"Logies en horeca" },
  "Toerisme & Horeca":             { code:"55/56",       desc:"Logies en horeca" },
  "Food & Beverages":              { code:"10/11",       desc:"Voedings- en genotmiddelen" },
  "Voeding & Dranken":             { code:"10/11",       desc:"Voedings- en genotmiddelen" },
  "Agriculture & Environment":     { code:"01/02",       desc:"Landbouw en milieu" },
  "Landbouw & Milieu":             { code:"01/02",       desc:"Landbouw en milieu" },
  "Renewable Energy & Sustainability":   { code:"35.11", desc:"Hernieuwbare energie" },
  "Hernieuwbare energie & Duurzaamheid": { code:"35.11", desc:"Hernieuwbare energie" },
  "Media & Entertainment":         { code:"59/60",       desc:"Film en media" },
  "Design & Creative":             { code:"74.10",       desc:"Gespecialiseerde ontwerp" },
  "Design & Creatief":             { code:"74.10",       desc:"Gespecialiseerde ontwerp" },
  "Sports & Fitness":              { code:"93.11/93.13", desc:"Sport en recreatie" },
  "Sport & Fitness":               { code:"93.11/93.13", desc:"Sport en recreatie" },
  "Non-profit & Social":           { code:"88/94",       desc:"Maatschappelijke dienstverlening" },
  "Non-profit & Sociaal":          { code:"88/94",       desc:"Maatschappelijke dienstverlening" },
  "Government & Public Sector":    { code:"84",          desc:"Openbaar bestuur" },
  "Overheid & Publieke sector":    { code:"84",          desc:"Openbaar bestuur" },
  "Persoonlijke diensten & Schoonheid": { code:"96.02",  desc:"Kappers en schoonheidsverzorging" },
  "Persoonlijke diensten & Beauty":     { code:"96.02",  desc:"Kappers en schoonheidsverzorging" },
};

// ── Sectors (same index = same sector across all 3 languages) ─
export const SECTORS = {
  ar: ["تكنولوجيا المعلومات والبرمجيات","ذكاء اصطناعي وبيانات","أمن سيبراني","تجارة إلكترونية","تجارة تجزئة","تجارة جملة وتوزيع","خدمات مهنية واستشارات","خدمات مالية وتأمين","محاسبة وقانون","عقارات وإنشاءات","تصنيع وصناعة","لوجستيات ونقل","صحة ورعاية طبية","صيدلة وتكنولوجيا حيوية","تعليم وتدريب","سياحة وضيافة وفنادق","أغذية ومشروبات","زراعة وبيئة","طاقة متجددة واستدامة","إعلام وترفيه وإنتاج","تصميم وإبداع وفنون","رياضة ولياقة بدنية","منظمات غير ربحية واجتماعية","حكومة وقطاع عام","خدمات شخصية وتجميل"],
  nl: ["IT & Software","AI & Data","Cybersecurity","E-commerce","Detailhandel","Groothandel & Distributie","Professionele diensten & Advies","Financiële diensten & Verzekering","Accountancy & Juridisch","Vastgoed & Bouw","Productie & Industrie","Logistiek & Transport","Zorg & Medisch","Farma & Biotech","Onderwijs & Training","Toerisme & Horeca","Voeding & Dranken","Landbouw & Milieu","Hernieuwbare energie & Duurzaamheid","Media & Entertainment","Design & Creatief","Sport & Fitness","Non-profit & Sociaal","Overheid & Publieke sector","Persoonlijke diensten & Schoonheid"],
  en: ["IT & Software","AI & Data","Cybersecurity","E-commerce","Retail","Wholesale & Distribution","Professional Services & Consulting","Financial Services & Insurance","Accounting & Legal","Real Estate & Construction","Manufacturing & Industry","Logistics & Transport","Healthcare & Medical","Pharma & Biotech","Education & Training","Tourism & Hospitality","Food & Beverages","Agriculture & Environment","Renewable Energy & Sustainability","Media & Entertainment","Design & Creative","Sports & Fitness","Non-profit & Social","Government & Public Sector","Persoonlijke diensten & Beauty"],
};

// ── Top 10 sectors ─────────────────────────────────────────────
export const TOP_SECTORS = [
  { rank:1,  icon:"💊", sbi:"21/72.11",    color:PURPLE,    ar:"صيدلة وتكنولوجيا حيوية",        nl:"Farma & Biotech",         en:"Pharma & Biotech",          margin:34, growth:9.2,  avgRevenue:"€2.1M", successRate:68, arDesc:"هولندا ثالث أكبر مُصدِّر للأدوية. هوامش ربح عالية.", nlDesc:"Nederland 3e farmaceutische exporteur.", enDesc:"Netherlands 3rd largest pharma exporter." },
  { rank:2,  icon:"💻", sbi:"62",          color:ORANGE,    ar:"تكنولوجيا المعلومات والبرمجيات", nl:"IT & Software",           en:"IT & Software",             margin:28, growth:11.4, avgRevenue:"€380K", successRate:65, arDesc:"42,000+ شركة IT في هولندا.", nlDesc:"42.000+ IT-bedrijven.", enDesc:"42,000+ IT companies." },
  { rank:3,  icon:"🤖", sbi:"62.09/63.11", color:"#0EA5E9", ar:"ذكاء اصطناعي وبيانات",          nl:"AI & Data",               en:"AI & Data",                 margin:31, growth:18.7, avgRevenue:"€520K", successRate:61, arDesc:"هولندا ضمن أفضل 5 دول أوروبية في AI.", nlDesc:"Nederland top 5 AI-landen.", enDesc:"Netherlands top 5 European AI countries." },
  { rank:4,  icon:"⚖️", sbi:"69",          color:BLUE,      ar:"محاسبة وقانون",                  nl:"Accountancy & Juridisch", en:"Accounting & Legal",        margin:26, growth:5.1,  avgRevenue:"€290K", successRate:72, arDesc:"من أعلى معدلات البقاء في السوق.", nlDesc:"Hoog overlevingspercentage.", enDesc:"Highest survival rates." },
  { rank:5,  icon:"🌱", sbi:"35.11",       color:GREEN,     ar:"طاقة متجددة واستدامة",           nl:"Hernieuwbare energie",    en:"Renewable Energy",          margin:22, growth:14.3, avgRevenue:"€750K", successRate:63, arDesc:"هدف هولندا 70% طاقة متجددة 2030.", nlDesc:"70% hernieuwbaar in 2030.", enDesc:"70% renewable target by 2030." },
  { rank:6,  icon:"🏥", sbi:"86/87/88",    color:RED,       ar:"صحة ورعاية طبية",                nl:"Zorg & Medisch",          en:"Healthcare & Medical",      margin:19, growth:6.8,  avgRevenue:"€410K", successRate:74, arDesc:"سوق رعاية صحية €100+ مليار.", nlDesc:"Zorgmarkt €100+ miljard.", enDesc:"€100+ billion healthcare market." },
  { rank:7,  icon:"🏗️", sbi:"41/68",      color:"#92400E", ar:"عقارات وإنشاءات",                nl:"Vastgoed & Bouw",         en:"Real Estate & Construction", margin:18, growth:4.2, avgRevenue:"€680K", successRate:60, arDesc:"نقص 300,000+ مسكن.", nlDesc:"Woningtekort 300.000+.", enDesc:"Housing shortage 300,000+ units." },
  { rank:8,  icon:"🚚", sbi:"49/52",       color:GOLD,      ar:"لوجستيات ونقل",                  nl:"Logistiek & Transport",   en:"Logistics & Transport",     margin:16, growth:7.9,  avgRevenue:"€920K", successRate:66, arDesc:"روتردام أكبر ميناء في أوروبا.", nlDesc:"Rotterdam grootste haven.", enDesc:"Rotterdam Europe's largest port." },
  { rank:9,  icon:"🛒", sbi:"47.91",       color:PURPLE,    ar:"تجارة إلكترونية",                nl:"E-commerce",              en:"E-commerce",                margin:15, growth:13.1, avgRevenue:"€340K", successRate:55, arDesc:"هولندا رائدة التجارة الإلكترونية.", nlDesc:"Nederland koploper e-commerce.", enDesc:"Netherlands leads e-commerce." },
  { rank:10, icon:"🎓", sbi:"85",          color:BLUE,      ar:"تعليم وتدريب",                   nl:"Onderwijs & Training",    en:"Education & Training",      margin:24, growth:8.6,  avgRevenue:"€220K", successRate:71, arDesc:"طلب متزايد على التدريب المهني.", nlDesc:"Groeiende vraag naar opleidingen.", enDesc:"Growing demand for training." },
];

// ── Freelance specializations ──────────────────────────────────
export const FREELANCE_DATA = [
  { id:"ai-ml",        icon:"🤖", cat:"tech",     color:PURPLE,    ar:"ذكاء اصطناعي / ML",  nl:"AI / Machine Learning",   en:"AI / Machine Learning",   rateMin:95, rateMax:175, demand:96, learnMin:12, learnMax:24, arDesc:"أعلى رواتب في هولندا. الطلب 3:1.", nlDesc:"Hoogste tarieven. Vraag overtreft aanbod.", enDesc:"Highest rates. Demand exceeds supply 3:1.", certs:["Google Professional ML Engineer","AWS Certified ML Specialty","TensorFlow Developer"], certUrls:["https://cloud.google.com/learn/certification","https://aws.amazon.com/certification","https://www.tensorflow.org/certificate"], courses:[{n:"Fast.ai (Free)",u:"https://course.fast.ai",free:true,mo:3},{n:"Coursera ML",u:"https://coursera.org/specializations/machine-learning-introduction",free:false,mo:4},{n:"DataCamp ML",u:"https://datacamp.com",free:false,mo:6}], tools:["Python","PyTorch","TensorFlow","Scikit-learn","Hugging Face"] },
  { id:"cloud",        icon:"☁️", cat:"tech",     color:"#0EA5E9", ar:"هندسة السحابة",      nl:"Cloud Architect",         en:"Cloud Architect",         rateMin:90, rateMax:160, demand:92, learnMin:8,  learnMax:18, arDesc:"المشاريع الحكومية تنتقل للسحابة.", nlDesc:"Overheidsprojecten migreren naar cloud.", enDesc:"Government fully migrating to cloud.", certs:["AWS Solutions Architect Pro","Azure Solutions Architect Expert","GCP Professional Architect"], certUrls:["https://aws.amazon.com/certification","https://learn.microsoft.com/certifications","https://cloud.google.com/learn/certification"], courses:[{n:"A Cloud Guru",u:"https://acloudguru.com",free:false,mo:6},{n:"Microsoft Learn (Free)",u:"https://learn.microsoft.com/training",free:true,mo:4},{n:"KodeKloud",u:"https://kodekloud.com",free:false,mo:5}], tools:["AWS","Azure","GCP","Terraform","Kubernetes","Docker"] },
  { id:"cybersec",     icon:"🔐", cat:"tech",     color:RED,       ar:"أمن المعلومات",      nl:"Cybersecurity",           en:"Cybersecurity",           rateMin:85, rateMax:155, demand:94, learnMin:10, learnMax:20, arDesc:"هجمات الإنترنت زادت 40%.", nlDesc:"Cyberaanvallen namen 40% toe.", enDesc:"Cyberattacks up 40% in NL.", certs:["CISSP","CEH - Certified Ethical Hacker","CompTIA Security+"], certUrls:["https://www.isc2.org/Certifications/CISSP","https://www.eccouncil.org/programs/certified-ethical-hacker-ceh/","https://www.comptia.org/certifications/security"], courses:[{n:"TryHackMe (Free)",u:"https://tryhackme.com",free:true,mo:4},{n:"SANS Institute",u:"https://www.sans.org",free:false,mo:6},{n:"Cybrary (Free)",u:"https://cybrary.it",free:true,mo:5}], tools:["Kali Linux","Wireshark","Metasploit","Splunk","Nmap"] },
  { id:"fullstack",    icon:"💻", cat:"dev",      color:ORANGE,    ar:"Full Stack Dev",     nl:"Full Stack Developer",    en:"Full Stack Developer",    rateMin:65, rateMax:120, demand:87, learnMin:8,  learnMax:18, arDesc:"React وNode.js الأكثر طلباً.", nlDesc:"React en Node.js meest gevraagd.", enDesc:"React and Node.js most demanded.", certs:["Meta Front-End Developer","AWS Developer Associate","MongoDB Developer"], certUrls:["https://coursera.org/professional-certificates/meta-front-end-developer","https://aws.amazon.com/certification","https://university.mongodb.com/certification"], courses:[{n:"The Odin Project (Free)",u:"https://www.theodinproject.com",free:true,mo:9},{n:"freeCodeCamp (Free)",u:"https://freecodecamp.org",free:true,mo:8},{n:"Scrimba",u:"https://scrimba.com",free:false,mo:6}], tools:["React","Node.js","TypeScript","Next.js","PostgreSQL"] },
  { id:"data-analyst", icon:"📊", cat:"data",     color:PURPLE,    ar:"محلل بيانات / BI",   nl:"Data Analyst / BI",       en:"Data Analyst / BI",       rateMin:55, rateMax:100, demand:85, learnMin:4,  learnMax:10, arDesc:"Power BI وTableau الأعلى طلباً.", nlDesc:"Power BI en Tableau meest gevraagd.", enDesc:"Power BI and Tableau most in demand.", certs:["Microsoft Power BI Analyst","Tableau Desktop Specialist","Google Data Analytics"], certUrls:["https://learn.microsoft.com/certifications/power-bi-data-analyst-associate/","https://www.tableau.com/learn/certification","https://coursera.org/professional-certificates/google-data-analytics"], courses:[{n:"Google Data Analytics",u:"https://coursera.org/professional-certificates/google-data-analytics",free:false,mo:6},{n:"Microsoft Learn (Free)",u:"https://learn.microsoft.com/training",free:true,mo:2},{n:"Kaggle (Free)",u:"https://kaggle.com/learn",free:true,mo:3}], tools:["Power BI","Tableau","Python","SQL","Excel"] },
  { id:"ux",           icon:"🎨", cat:"design",   color:"#EC4899", ar:"UX/UI Designer",     nl:"UX/UI Designer",          en:"UX/UI Designer",          rateMin:55, rateMax:105, demand:80, learnMin:5,  learnMax:12, arDesc:"أمستردام عاصمة التصميم في أوروبا.", nlDesc:"Amsterdam is de designhoofdstad.", enDesc:"Amsterdam is Europe's design capital.", certs:["Google UX Design Certificate","Interaction Design Foundation","Nielsen Norman UX"], certUrls:["https://coursera.org/professional-certificates/google-ux-design","https://www.interaction-design.org/courses","https://www.nngroup.com/ux-certification/"], courses:[{n:"Google UX Design",u:"https://coursera.org/professional-certificates/google-ux-design",free:false,mo:6},{n:"IDF Foundation",u:"https://interaction-design.org",free:false,mo:6},{n:"Figma (Free)",u:"https://help.figma.com",free:true,mo:2}], tools:["Figma","Sketch","Adobe XD","InVision","Miro"] },
  { id:"marketing",    icon:"📣", cat:"marketing",color:GOLD,      ar:"تسويق رقمي / SEO",  nl:"Digital Marketing / SEO", en:"Digital Marketing / SEO", rateMin:45, rateMax:95,  demand:78, learnMin:3,  learnMax:8,  arDesc:"سهل الدخول لكن المنافسة عالية.", nlDesc:"Laagste instapdrempel.", enDesc:"Low barrier but high competition.", certs:["Google Ads (Free)","HubSpot Marketing (Free)","Meta Blueprint"], certUrls:["https://skillshop.google.com","https://academy.hubspot.com","https://www.facebook.com/business/learn/certification"], courses:[{n:"Google Digital Garage (Free)",u:"https://learndigital.withgoogle.com",free:true,mo:2},{n:"HubSpot Academy (Free)",u:"https://academy.hubspot.com",free:true,mo:2},{n:"Semrush Academy (Free)",u:"https://www.semrush.com/academy/",free:true,mo:2}], tools:["Google Ads","Meta Ads","SEMrush","Ahrefs","HubSpot","GA4"] },
];

// ── Dutch job sites ────────────────────────────────────────────
export const JOB_SITES = [
  { name:"LinkedIn",          color:"#0077B5", url:(q,l)=>`https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(q)}&location=${encodeURIComponent(l||"Nederland")}` },
  { name:"Indeed NL",         color:"#003A9B", url:(q,l)=>`https://nl.indeed.com/jobs?q=${encodeURIComponent(q)}&l=${encodeURIComponent(l||"Nederland")}` },
  { name:"Werk.nl",           color:"#009FE3", url:(q,l)=>`https://www.werk.nl/werk-vinden/vacatures/?q=${encodeURIComponent(q)}&locatie=${encodeURIComponent(l||"")}` },
  { name:"Monsterboard",      color:"#6B00A3", url:(q,l)=>`https://www.monsterboard.nl/vacatures?q=${encodeURIComponent(q)}&where=${encodeURIComponent(l||"Nederland")}` },
  { name:"Nat. Vacaturebank", color:"#E4000F", url:(q,l)=>`https://www.nationalevacaturebank.nl/vacature/zoeken?query=${encodeURIComponent(q)}&location=${encodeURIComponent(l||"")}` },
  { name:"Randstad",          color:"#005C8A", url:(q,l)=>`https://www.randstad.nl/vacatures/?q=${encodeURIComponent(q)}` },
  { name:"Tempo-Team",        color:"#FF6200", url:(q,l)=>`https://www.tempo-team.nl/vacatures?q=${encodeURIComponent(q)}&location=${encodeURIComponent(l||"")}` },
  { name:"Intermediair",      color:"#333333", url:(q,l)=>`https://www.intermediair.nl/vacatures?q=${encodeURIComponent(q)}&city=${encodeURIComponent(l||"")}` },
];

// ── News categories ────────────────────────────────────────────
export const NEWS_CATS = {
  tax:      { ar:"ضرائب",       nl:"Belastingen", en:"Taxes",     color:RED,    icon:"💰" },
  business: { ar:"أعمال",       nl:"Ondernemen",  en:"Business",  color:BLUE,   icon:"🏢" },
  law:      { ar:"قوانين",      nl:"Wetgeving",   en:"Law",       color:PURPLE, icon:"⚖️" },
  subsidy:  { ar:"دعم حكومي",  nl:"Subsidies",   en:"Subsidies", color:GREEN,  icon:"🌱" },
  economy:  { ar:"اقتصاد",      nl:"Economie",    en:"Economy",   color:GOLD,   icon:"📊" },
  housing:  { ar:"عقارات",      nl:"Vastgoed",    en:"Housing",   color:"#92400E", icon:"🏠" },
};

// ── Translations ───────────────────────────────────────────────
export const T = {
  ar: {
    dir:"rtl", font:"Tahoma, Arial, sans-serif",
    tagline:"محلل الأعمال",
    ideaLabel:"صف فكرتك التجارية", sectorLabel:"القطاع",
    ideaPlaceholder:"مثلاً: متجر إلكتروني لبيع منتجات العناية في أمستردام...",
    analyzeBtn:"تحليل الفكرة بواسطة الوكلاء", runningBtn:"الوكلاء يعملون...",
    agents:[
      { id:"market",     icon:"🕵️", title:"تحليل السوق",    sub:"",          color:ORANGE },
      { id:"legal",      icon:"⚖️",  title:"الإطار القانوني", sub:"", color:BLUE   },
      { id:"innovation", icon:"🚀",  title:"الابتكار والدعم", sub:"",        color:GREEN  },
      { id:"finance",    icon:"💰",  title:"التحليل المالي",  sub:"",     color:PURPLE },
    ],
    prompts:{
      market:(i,s)=>`أنت محلل سوق خبير في هولندا. حلل: "${i}" في قطاع ${s}. 4 جمل: حجم السوق، المنافسة، النمو. بالعربية. لا markdown.`,
      legal:(i,s)=>`أجب بالعربية فقط. أنت مستشار قانوني في هولندا. اكتب 4 جمل عملية ومباشرة عن: تسجيل الفكرة "${i}" في قطاع ${s} بـ KVK، نوع الكيان القانوني، متطلبات BTW، والتراخيص اللازمة. بدون عناوين أو markdown.`,
      innovation:(i,s)=>`أجب بالعربية فقط. أنت خبير ابتكار في هولندا. اكتب 4 جمل عملية عن الفكرة "${i}" في قطاع ${s}: الدعم الحكومي المتاح من RVO، فرص الابتكار والتقنية، الاستدامة، والمنح. بدون عناوين أو markdown.`,
      finance:(i,s)=>`أنت محلل مالي هولندي. حلل: "${i}" في ${s}. اكتب mainRisks وstrengths وsummary بالعربية. riskLevel: منخفض أو متوسط أو عالي. JSON فقط:\n{"successRate":NUMBER,"failureRate":NUMBER,"roi12m":NUMBER,"roi36m":NUMBER,"breakEvenMonths":NUMBER,"initialInvestment":"STRING","monthlyRevenue":"STRING","netMargin":NUMBER,"riskLevel":"منخفض|متوسط|عالي","year1Profit":"STRING","year3Profit":"STRING","mainRisks":["S","S","S"],"strengths":["S","S","S"],"summary":"STRING","dataSource":"STRING"}`,
    },
    idleText:"في انتظار التفعيل...", workingText:"الوكيل يحلل...", doneLabel:"✓ مكتمل",
    resultsTitle:"ملخص دراسة الجدوى",
    tab1:"ملخص التنفيذ", tab2:"📊 التحليل المالي", tab3:"الخطوات",
    successLabel:"نسبة النجاح", failureLabel:"نسبة الخسارة",
    roi12:"عائد الاستثمار — سنة 1", roi36:"عائد الاستثمار — 3 سنوات",
    breakEven:"نقطة التعادل", initialInv:"الاستثمار الأولي",
    monthlyRev:"الإيراد الشهري", netMargin:"هامش الربح",
    year1Profit:"ربح سنة 1", year3Profit:"ربح سنة 3",
    riskLabel:"مستوى المخاطرة", mainRisks:"المخاطر الرئيسية", strengths:"نقاط القوة",
    summaryLabel:"الملخص المالي", sourceLabel:"مصادر البيانات",
    riskLow:"منخفض", riskMed:"متوسط", riskHigh:"عالي",
    finError:"⚠️ تعذّر تحليل البيانات المالية",
    kpis:[{label:"الجدوى الفنية",value:"عالية",color:GREEN},{label:"رغبة المستخدم",value:"مؤشرات قوية",color:BLUE},{label:"التوصية",value:"المضي قدماً",color:ORANGE}],
    recommendation:"بناءً على تحليل الوكلاء، تُظهر فكرتك إمكانية تنفيذ جيدة في السوق الهولندي.",
    recommendationLabel:"توصية استراتيجية:",
    steps:["تسجيل النشاط في KVK (kvk.nl/inschrijven)","التسجيل في Belastingdienst للـ BTW","بدء حملة تحقق من الجمهور المستهدف"],
    stepsProgress:(n)=>`${n} / 3 خطوات مكتملة`,
    footer:"© 2025 BizAnalyzer.nl — جميع الحقوق محفوظة",
    months:"شهر", rerunHint:"🔄 يتم إعادة التحليل...", retryBtn:"🔄 إعادة تحليل الوكيل المالي",
    navHome:"🏠 الرئيسية", navTop:"🏆 أكثر ربحاً", navFreelance:"💼 أجور المستقلين",
    navJobs:"🔎 فرص عمل", navNews:"📰 أخبار", navBlog:"📝 مدونة", navAbout:"ℹ️ عن الموقع",
    navContact:"✉️ تواصل", navPrivacy:"🔒 الخصوصية",
  },
  nl: {
    dir:"ltr", font:"Segoe UI, Arial, sans-serif",
    tagline:"AI Bedrijfsanalist",
    ideaLabel:"Beschrijf jouw bedrijfsidee", sectorLabel:"Sector",
    ideaPlaceholder:"Bijv.: Webshop voor natuurlijke huidverzorging in Amsterdam...",
    analyzeBtn:"Analyseer met specialisten", runningBtn:"Agents analyseren...",
    agents:[
      { id:"market",     icon:"🕵️", title:"Marktanalist",       sub:"",          color:ORANGE },
      { id:"legal",      icon:"⚖️",  title:"Juridisch Adviseur", sub:"", color:BLUE   },
      { id:"innovation", icon:"🚀",  title:"Innovatie-expert",   sub:"",        color:GREEN  },
      { id:"finance",    icon:"💰",  title:"Financieel Analist", sub:"",     color:PURPLE },
    ],
    prompts:{
      market:(i,s)=>`Je bent marktanalist Nederland. Analyseer: "${i}" in ${s}. 4 zinnen: marktvraag, concurrentie, groei. Nederlands. Geen markdown.`,
      legal:(i,s)=>`Antwoord alleen in het Nederlands. Je bent juridisch adviseur. Schrijf 4 praktische zinnen over: KVK-registratie voor "${i}" in ${s}, rechtsvorm, BTW-plicht en benodigde vergunningen. Geen titels of markdown.`,
      innovation:(i,s)=>`Antwoord in het Nederlands. Schrijf 4 praktische zinnen over innovatiemogelijkheden voor "${i}" in ${s}: beschikbare RVO-subsidies, technologische kansen, duurzaamheidseisen en innovatieondersteuning. Geen titels of markdown.`,
      finance:(i,s)=>`Je bent financieel analist Nederland. Analyseer: "${i}" in ${s}. Schrijf mainRisks, strengths en summary in het Nederlands. riskLevel: laag, gemiddeld of hoog. Alleen JSON:\n{"successRate":NUMBER,"failureRate":NUMBER,"roi12m":NUMBER,"roi36m":NUMBER,"breakEvenMonths":NUMBER,"initialInvestment":"STRING","monthlyRevenue":"STRING","netMargin":NUMBER,"riskLevel":"laag|gemiddeld|hoog","year1Profit":"STRING","year3Profit":"STRING","mainRisks":["S","S","S"],"strengths":["S","S","S"],"summary":"STRING","dataSource":"STRING"}`,
    },
    idleText:"Wachten...", workingText:"Analyseren......", doneLabel:"✓ Voltooid",
    resultsTitle:"Haalbaarheidsanalyse",
    tab1:"Uitvoeringsoverzicht", tab2:"📊 Financiële Analyse", tab3:"Stappen",
    successLabel:"Slagingspercentage", failureLabel:"Mislukkingspercentage",
    roi12:"ROI — Jaar 1", roi36:"ROI — 3 jaar",
    breakEven:"Break-even", initialInv:"Initiële investering",
    monthlyRev:"Maandomzet", netMargin:"Nettomarge",
    year1Profit:"Winst jaar 1", year3Profit:"Winst jaar 3",
    riskLabel:"Risiconiveau", mainRisks:"Risico's", strengths:"Sterktes",
    summaryLabel:"Financiële samenvatting", sourceLabel:"Databronnen",
    riskLow:"Laag", riskMed:"Gemiddeld", riskHigh:"Hoog",
    finError:"⚠️ Kon financiële data niet verwerken",
    kpis:[{label:"Technische haalbaarheid",value:"Hoog",color:GREEN},{label:"Marktvraag",value:"Sterk signaal",color:BLUE},{label:"Aanbeveling",value:"Ga door",color:ORANGE}],
    recommendation:"Op basis van de analyse toont het idee goede haalbaarheid op de Nederlandse markt.",
    recommendationLabel:"Strategische aanbeveling:",
    steps:["Inschrijven bij KVK (kvk.nl/inschrijven)","BTW-registratie via Belastingdienst","Doelgroepvalidatie starten (MVP)"],
    stepsProgress:(n)=>`${n} / 3 stappen voltooid`,
    footer:"© 2025 BizAnalyzer.nl — Alle rechten voorbehouden",
    months:"mnd", rerunHint:"🔄 Analyse wordt herhaald...", retryBtn:"🔄 Financiële agent opnieuw",
    navHome:"🏠 Home", navTop:"🏆 Top Sectoren", navFreelance:"💼 ZZP Tarieven",
    navJobs:"🔎 Vacatures", navNews:"📰 Nieuws", navBlog:"📝 Blog", navAbout:"ℹ️ Over ons",
    navContact:"✉️ Contact", navPrivacy:"🔒 Privacy",
  },
  en: {
    dir:"ltr", font:"Segoe UI, Arial, sans-serif",
    tagline:"AI Business Analyzer",
    ideaLabel:"Describe your business idea", sectorLabel:"Sector",
    ideaPlaceholder:"E.g.: Online store for natural skincare products in Amsterdam...",
    analyzeBtn:"Analyze with AI agents", runningBtn:"Agents analyzing...",
    agents:[
      { id:"market",     icon:"🕵️", title:"Market Agent",     sub:"",          color:ORANGE },
      { id:"legal",      icon:"⚖️",  title:"Legal Agent",      sub:"", color:BLUE   },
      { id:"innovation", icon:"🚀",  title:"Innovation Agent", sub:"",        color:GREEN  },
      { id:"finance",    icon:"💰",  title:"Finance Agent",    sub:"",     color:PURPLE },
    ],
    prompts:{
      market:(i,s)=>`You are a Dutch market analyst. Analyze: "${i}" in ${s}. 4 sentences: demand, competition, growth. English. No markdown.`,
      legal:(i,s)=>`Reply in English only. You are a Dutch legal advisor. Write 4 practical sentences about: KVK registration for "${i}" in ${s}, legal structure, VAT obligations, and required permits. No headings or markdown.`,
      innovation:(i,s)=>`Reply in English only. Write 4 practical sentences about innovation opportunities for "${i}" in ${s}: available RVO grants, technology opportunities, sustainability requirements, and innovation support programs. No headings or markdown.`,
      finance:(i,s)=>`You are a Dutch financial analyst. Analyze: "${i}" in ${s}. Write mainRisks, strengths and summary in English. riskLevel: low, medium or high. JSON only:\n{"successRate":NUMBER,"failureRate":NUMBER,"roi12m":NUMBER,"roi36m":NUMBER,"breakEvenMonths":NUMBER,"initialInvestment":"STRING","monthlyRevenue":"STRING","netMargin":NUMBER,"riskLevel":"low|medium|high","year1Profit":"STRING","year3Profit":"STRING","mainRisks":["S","S","S"],"strengths":["S","S","S"],"summary":"STRING","dataSource":"STRING"}`,
    },
    idleText:"Waiting...", workingText:"Analyzing......", doneLabel:"✓ Done",
    resultsTitle:"Feasibility Study",
    tab1:"Execution Overview", tab2:"📊 Financial Analysis", tab3:"Steps",
    successLabel:"Success Rate", failureLabel:"Failure Rate",
    roi12:"ROI — Year 1", roi36:"ROI — 3 Years",
    breakEven:"Break-even", initialInv:"Initial Investment",
    monthlyRev:"Monthly Revenue", netMargin:"Net Margin",
    year1Profit:"Year 1 Profit", year3Profit:"Year 3 Profit",
    riskLabel:"Risk Level", mainRisks:"Main Risks", strengths:"Strengths",
    summaryLabel:"Financial Summary", sourceLabel:"Data Sources",
    riskLow:"Low", riskMed:"Medium", riskHigh:"High",
    finError:"⚠️ Could not parse financial data",
    kpis:[{label:"Technical Feasibility",value:"High",color:GREEN},{label:"Market Demand",value:"Strong signal",color:BLUE},{label:"Recommendation",value:"Move forward",color:ORANGE}],
    recommendation:"Based on analysis, your idea shows good feasibility in the Dutch market.",
    recommendationLabel:"Strategic recommendation:",
    steps:["Register at KVK (kvk.nl/inschrijven)","VAT registration via Belastingdienst","Start target audience validation (MVP)"],
    stepsProgress:(n)=>`${n} / 3 steps completed`,
    footer:"© 2025 BizAnalyzer.nl — All rights reserved",
    months:"mo", rerunHint:"🔄 Re-analyzing in selected language...", retryBtn:"🔄 Retry Finance Agent",
    navHome:"🏠 Home", navTop:"🏆 Top Sectors", navFreelance:"💼 Freelance Rates",
    navJobs:"🔎 Jobs", navNews:"📰 News", navBlog:"📝 Blog", navAbout:"ℹ️ About",
    navContact:"✉️ Contact", navPrivacy:"🔒 Privacy",
  },
};
